### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by jerryowusu**
## Description

An educational project for making a React calculator.  This pull request implements unit test with React Testing Library and snapshots with Jest.

### General requirements

- [x] There are **no linter errors**.
- [x] Followed the **GitFlow**.
- [x] The documentation is **professional**.

### HTML/CSS requirements

- [x] Followed best practices for JavaScript

### Project requirements

- [x] Set up React Testing Library
- [x] Write unit tests for the files operate.js and calculate.js using Jest.
- [x]  Create unit tests for all React components:
- [x] Use Jest snapshots to test the components.
- [x] Use React Testing Library to simulate user interaction.

---
Thank you for taking the time to review this pull request.

### CODE REVIEW

**Comment by moise10r** [comment]
This is a pair programming project, I can see only one developer worked on this project. 
Tell me do you have a partner?

**Review by moise10r — CHANGES_REQUESTED** [review]
### Hi TEAM,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Gitflow was correctly used.  ✔️   
- Usage of Jest snapshots for testing all the components.✔️
- Usage of React Testing Library to simulate user interaction. ✔️  
- All the tests are passing as they should, keep rocking :rocket: 
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [x] This is a pair programming project, I can see only one developer worked on this project. Please make sure that both of you push commit messages. The reviewer will check the commit history to make sure that everybody has contributed code to the project.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jerryowusu** [comment]
Okay, well noted @moise10r

**Comment by jerryowusu** [comment]
Please we have gone through the project and updated it according to the rules and specifications of pair-programming.
Thank you for taking the time to review this project, hope you enjoy yourself whiles reviewing. 👍

**Review by bimbolabuari — APPROVED** [review]
Hi Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jerryowusu** [comment]
Wow! That was fast! Thanks @bimbolabuari

**Comment by mwafrika** [comment]
Thank you @moise10r  @bimbolabuari  for your review

**Pull request merged**
