### PR TITLE
setup project

### PR DESCRIPTION
**Pull request by jerryowusu**
## Setup project

In this milestone I:

- [x] created a new react app
- [x] set up linters
- [x]  setup a Gitflow 
- [x] updated the readme file
- [x] added a license 

## General requirements

- [x]  No linter errors
- [x]  Correct Gitflow
- [x] Application run in browser with no errors

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
# STATUS: Request Changes! ♻️

Hi @jerryowusu , 

You have done a great job so far. However, there are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes :recycle: :red_circle: 

- [x] Please let's make sure that our application runs in the browser without console error. Also, npm start does not start up your application. Kindly fix these minor issues and submit your project once more for approval. 
- [x] Let's make sure that our README file is descriptive and professional. Let's stick to t[his template](https://github.com/microverseinc/readme-template) from Microverse. Customize the template to the needs of your project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jerryowusu** [comment]
- [x] Hello @FrederickMih, I have check on my PC and a linux machine and I can assure you that the program runs correctly with npm start and no errors in the console as you allerged. Find a snapshot below of the project running in the browser.



Screenshot (42)


 (Maybe you forgot to do npm install) 

- [x] I have updated the readme file. Others will be added in the as the project progresses

**Comment by FrederickMih** [comment]
- Hi @jerryowusu, submit your project once more :pray:

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @jerryowusu, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jerryowusu** [comment]
Thanks @Mihndim2020

**Pull request merged**
